### PR TITLE
Fix `.isOnLadder()` condition

### LINKED ISSUE #108: Feature lists is not updated
https://github.com/PrismarineJS/prismarine-physics/blob/88444cdfbfaf6f099d8431b4a158eb5006f7ae9c/lib/features.json#L23-L25

For example, this list should contain every version after `1.14`. I think we should add a better versioning syntax like `>= 1.14`.

### LINKED ISSUE #109: Cannot climb trapdoors dirrectly above ladders
Ref: https://minecraft.wiki/w/Ladder#Climbing

> In Java Edition, when a [trapdoor](https://minecraft.wiki/w/Trapdoor) satisfies the following conditions, it also becomes climbable:
> 
>  + The trapdoor is placed directly above a ladder.
>  + The trapdoor is opened.
>  + The trapdoor and the ladder directly below it face the same direction.

### PR DESCRIPTION
**Pull request by szdytom**
The problem: I have noticed the bot cannot climb trapdoors that is directly above ladders (#109). I have also noticed that in 1.20.1 the bot cannot jump to climb ladders (#108).

In this pull request:
- I've added a new feature `climableTrapdoor` to indicate whether the trapdoors is climbable. [Reference: Trapdoor History - Minecraft Wiki](https://minecraft.wiki/w/Trapdoor#History)
- I've added code in function `isOnLadder` to handdle trapdoors.
- I've added a few missing versions to `features.json`

Fixes #108
Fixes #109
Closes #110

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -421,7 +436,22 @@ function Physics (mcData, world) {
...
+    //  1. The trapdoor is placed directly above a ladder.
+    //  2. The trapdoor is opened.
+    //  3. The trapdoor and the ladder directly below it face the same direction.
+    if (supportFeature('climbableTrapdoor') && trapdoorIds.has(block.type)) {
+      const blockBelow = world.getBlock(pos.offset(0, -1, 0))
+      if (blockBelow.type !== ladderId) { return false } // condition 1.
+      if (!block.getProperties().open) { return false } // condition 2.
+      if (block.getProperties().facing !== blockBelow.getProperties().facing) { return false } // condition 3
+      return true
+    }
```
Comment (extremeheat) [inline index.js:452]: These are expensive calls, and hard to optimize for the JIT compiler as there's many allocations here. For physics code that needs to be run at high performance, it's not good. There should be a more optimal way to do this.

Comment (szdytom) [reply index.js:452]: Sorry I don't understand. Is that `.getProperties()` the expensive call, or is it `world.getBlock()`?

Comment (extremeheat) [reply index.js:452]: This function is hot code, as it's run on every movement. Especially for things like pathfinding, it will be a bottleneck as several temporary allocations are done and end up as garbage.

Calling check feature is slow and can require iterating over all the features, so that instead can be a top level boolean. The 3 calls getProperties to all create copies of property data with property access. That can be done once.

Comment (szdytom) [reply index.js:452]: You are right, but this is partly due to both `supportFeature` and `.getProperties()` is badly designed and implemented. `supportFeature` should have used numeric ids instead of strings and `.getProperties()` should always return the same object (pointer).

Comment (szdytom) [reply index.js:452]: p.s. This branch is defiantly **not** hot code. In practice, the bot will not frequently step into trapdoors

Comment (extremeheat) [reply index.js]: It is hot, and isOnLadder is called twice on each movement tick. Also, all the code inside a hot function, whether it's behind a branch or not is factored into whether or not a function can be optimized or not.

https://github.com/PrismarineJS/prismarine-physics/blob/d29774ae4ca426d87a5209a9dc5e92aa45458b7c/index.js#L580

Comment (extremeheat) [reply index.js]: Ideally we also look into if getBlock() calls themselves can be faster, perhaps by using state IDs, but that's beyond the scope of the PR

Comment (Vakore) [reply index.js]: https://github.com/PrismarineJS/prismarine-block/blob/38e8e877e43c1ad29a90d23102a6c23e0d95ebbd/index.js#L263

Would adding a new function to prismarine-block help with this?
getPropertiesPointer () {
    //whichever of these would help solve this ladder issue
    return this._properties;
    return this.computedStates;
}


Alternatively making the feature passable as a boolean so that things simulating physics need not worry about this unless they toggle it on, but applied movement would still work fine. Access to the feature, even in a cumbersome manner with room for optimization, will still give people a solution.

**Comment by rom1504** [comment]
can you take another look @extremeheat ?

**Review by extremeheat — APPROVED** [review]
LGTM, we can use block._properties instead of getProperties() (which creates a temporary object), but otherwise good

**Comment by szdytom** [comment]
would you take another look please, I've updated the code. Thanks
